spring:
  application:
    name: marketplace-demo
  datasource:
    url: jdbc:mysql://localhost:3306/amazon_clone?createDatabaseIfNotExist=true
    username: root
    password: Gudmord92!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop